const ADD_ITEM = 'ADD_ITEM';
const UPDATE_ITEM = 'UPDATE_ITEM';
const DELETE_ITEM = 'DELETE_ITEM';
const RESET_ITEMS = 'RESET_ITEMS';
const SET_IS_LOADING = 'SET_IS_LOADING';

export {
	ADD_ITEM,
	UPDATE_ITEM,
	DELETE_ITEM,
	RESET_ITEMS,
	SET_IS_LOADING,
};
